services:
  - type: web
    name: textroleplay-backend
    env: node
    rootDir: ./backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production