services:
  - type: web
    name: textroleplay
    env: node
    buildCommand: node render-build.js
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production